services:
  postgres_payments:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=payments_db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5434:5432'
